<a href="https://colab.research.google.com/github/Roheya20/First-session/blob/main/Week1_Data_Cleaning_Roheya_Touray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Roheya Touray

Week1: Data cleaning and analysis

In [100]:
import pandas as pd

In [101]:
df = pd.read_csv('applicants.csv')

In [102]:
df.shape

(68, 7)

In [103]:
df.head()

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Grace Njeri,grace.njeri25@gmail.com,0788963003,Web Development,ALU,2026-05-25,Selected
1,Fatou Jallow,fatou.jallow44@gmail.com,0788985669,Machine Learning,ALU,2026-06-13,Rejected
2,Sara Ahmed,sara.ahmed35@gmail.com,0788982709,Web Development,ALU,2026-06-04,Under Review
3,Aminata Koroma,aminata.koroma16@gmail.com,0788150626,AI,ALU,2026-05-16,Rejected
4,Linda Brown,linda.brown31@gmail.com,0788851138,Machine Learning,ALU,2026-05-31,Selected

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    67 non-null     object
 1   Email             67 non-null     object
 2   Phone             68 non-null     object
 3   Domain Applied    68 non-null     object
 4   University        65 non-null     object
 5   Application Date  68 non-null     object
 6   Status            67 non-null     object
dtypes: object(7)
memory usage: 3.8+ KB

In [105]:
df.isnull().sum()

Applicant Name      1
Email               1
Phone               0
Domain Applied      0
University          3
Application Date    0
Status              1
dtype: int64

In [106]:
df.duplicated().sum()

np.int64(3)

The dataset has 68 rows and 7 columns. Email has 1 missing value, University has 3 missing values, Applicant name has 1 missing value, Status has 1 missing value, there are 3 exact duplicate rows.

In [107]:
df = df.dropna(subset= ['Applicant Name'])

In [108]:
df.isnull().sum()

Applicant Name      0
Email               1
Phone               0
Domain Applied      0
University          2
Application Date    0
Status              1
dtype: int64

I dropped the row with missing Application Name because a nameless application isn't for outreach

In [109]:
df = df.dropna(subset=['Email'])

In [110]:
df.isnull().sum()

Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          2
Application Date    0
Status              1
dtype: int64

I dropped rows with missing email beacuase an application without an email can't be reached.

In [111]:
df['University'] = df['University'].fillna('Not specified')

In [112]:
df.isnull().sum()

Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              1
dtype: int64

I filled missing University with 'Not Specified' instead of dropping it, since it's not essential to determining applcation status.

In [113]:
df['Status']= df['Status'].fillna('Under Review')

In [114]:
df.isnull().sum()

Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

In [115]:
df = df.drop_duplicates(subset=['Email'], keep='first')

In [116]:
df.duplicated().sum()

np.int64(0)

I had 3 duplicates, after dropping  the number of duplicates beacame 0. I chose to use email because with the email you can check duplicate applications by the same email.

In [117]:
domain_mapping ={
    'web dev': 'Web Development',
    'webdev': 'Web Development',
    'web development': 'Web Development',
}

In [118]:
df['Domain Applied'] = df['Domain Applied'].map(domain_mapping)

In [119]:
df['Status'] = df['Status'].str.strip().str.title()

In [120]:
df['Application Date'] = pd.to_datetime(df['Application Date'], errors='coerce')

In [121]:
df['Application Date'].isnull().sum()

np.int64(6)

In [122]:
df['Phone'] = df['Phone'].str.replace('-', '', regex=False).str.replace('', '', regex=False)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63 entries, 0 to 67
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    63 non-null     object
 1   Email             63 non-null     object
 2   Phone             63 non-null     object
 3   Domain Applied    2 non-null      object
 4   University        63 non-null     object
 5   Application Date  57 non-null     datetime64[ns]
 6   Status            63 non-null     object
dtypes: datetime64[ns](1), object(6)
memory usage: 3.9+ KB

In [124]:
df.shape

(63, 7)

In [125]:
df.isnull().sum()

Applicant Name       0
Email                0
Phone                0
Domain Applied      61
University           0
Application Date     6
Status               0
dtype: int64

In [126]:
df.duplicated().sum()

np.int64(0)

Data Quality Summary
Starting dataset: 68 rows, 7 columns

Issues found:
- 1 missing value in Application Name, 1 missing value in Email, 3 missing values in university, 1 missing value in status
- 3 exact duplicate rows, plus 3 additional duplicate applications Identified my matching Email.
- Domain Applied contained inconsistent spellings and capitalisation, including variations such as web dev, Web dev, WEB DEV.
- Application date values used inconsistent formats and needed to be converted to a proper datetime type
- Phone numbers contained inconsistent spacing and dash formatting.
- Status values had inconsistent capitalisation, such as Selected, selected, and SELECTED

Actions taken:
- Dropped 1 row with missing Application Name (unusable without identification)
- Filled missing University with "Not Specified" (non-critical field)
-Filled missing Status with "Under Review" (default for unprocessed applications)
- Removed 6 duplicate rows total (3 exact, 3 by matching email)
- Converted Application Date to the proper datetime format.
- Cleaned phone number formatting for consistency

Final dataset: 63 rows, 7 columns, no missing values in critical fields, no duplicates, consistent formatting throughout.

In [127]:
df.to_csv('applicants_cleaned.csv', index=False)